# Snapshot date of OSM extracts for study countries
OSM_SNAPSHOT_DATE: 2026-09-01
# Target MobilityDatabase GTFS snapshot date
MDB_SNAPSHOT_DATE: 2026-09-01
# Minimum population of a functional urban area (FUA)
MIN_FUA_POPU: 200000
# Start and end dates of public transport services in GTFS data
SERVICE_START: 2023-01-01
SERVICE_END: 2026-12-31
# Radius/bandwidth (metres) used in clustering of nearby stops
STOP_CLUSTER_RADIUS: 400
# Buffer radius (metres) of stops around stations for intracity trips
STN_BUFFER_RADIUS: 400
# Maximum distance (metres) of a station to its nearest OSM junction
MAX_STN_OSM_OFFSET: 5000
# Catchment radius (km) of an airport for FUA centroid mapping
AIRPORT_CATCH_RADIUS: 150